// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAdminRole = "admin_role"

// AdminRole 管理员角色表
type AdminRole struct {
	ID       int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AdminID  int64     `gorm:"column:admin_id;not null;comment:管理员id" json:"admin_id"` // 管理员id
	RoleID   int64     `gorm:"column:role_id;not null;comment:角色id" json:"role_id"`    // 角色id
	CreateAt time.Time `gorm:"column:create_at;not null" json:"create_at"`
	UpdateAt time.Time `gorm:"column:update_at;not null" json:"update_at"`
	CreateBy int64     `gorm:"column:create_by;not null" json:"create_by"`
	UpdateBy int64     `gorm:"column:update_by;not null" json:"update_by"`
}

// TableName AdminRole's table name
func (*AdminRole) TableName() string {
	return TableNameAdminRole
}
